### ISSUE TITLE
Stack: namespaced templates

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/haskell-hackathon#6]
https://github.com/commercialhaskell/stack/issues/4039

**Comment by johnmendonca** [comment]
myself and @lylek are looking at this

**Comment by johnmendonca** [comment]
@lylek I looked at this today and added support for gitlab and bitbucket, which changed the parse function.

https://github.com/commercialhaskell/stack/commit/64be8a2882e2921cec3b05fb4325291527544df7

**Comment by lylek** [comment]
Great, thanks, John! I'm a little confused as to how these commits got into the commercialhaskell/stack repo though - I haven't issued a pull request yet.

**Comment by johnmendonca** [comment]
@lylek Yeah I noticed that too.  I committed to the branch on my fork though, so I figured it was github trying to do something fancy.

Let me know if you want to add more to this soon, I just got home and might look at it tomorrow.  Trying to figure out the relRequest part...

**Comment by lylek** [comment]
Hi John - your changes look good. Turns out I had a small change locally sitting around, so I pushed it. I also want to update the documentation.

I'm not sure how to merge all this - you do a pull request for your fork to me, then I do a pull request for my fork to the commercialstack repo?

**Comment by lylek** [comment]
Argh, the changes I was making were not quite done. Need to make sure e.g. I'm returning the right error.

**Comment by lylek** [comment]
I was thinking it would be nice if "stack templates" could also take an argument for where to pull the list, similar to "new" but without the template name. But perhaps that's for another ticket.

**Comment by johnmendonca** [comment]
No prob, I would say it's probably better for you to merge my branch locally if you are still currently adding things.

The following is copy/pastable (I chose rebase, but you can put merge instead if you want):
git remote add johnmendonca https://github.com/johnmendonca/stack.git && \\
git fetch johnmendonca && \\
git rebase johnmendonca/4039-namespaced-templates

**Comment by johnmendonca** [comment]
Yeah, there was also the matter of the template list showing a cleaner help output which I think should also be separate at this point.

Having the repo shorthand and handling it properly with respect to relative file paths is good enough for me for this one :smiley:

**Comment by johnmendonca** [comment]
Oops I had to edit my git commands to be copyable, the backslashes disappeared at first.

**Comment by lylek** [comment]
Sorry it's taken so long, but I think I'm finally done with my changes. I just updated the help for the TEMPLATE_NAME parameter. Want to rebase/merge in your changes?

**Comment by johnmendonca** [comment]
Looks good.  I have rebased my branch and force pushed.  

Full diff is here: https://github.com/commercialhaskell/stack/compare/master...johnmendonca:4039-namespaced-templates

**Comment by lylek** [comment]
Thanks, John. I think there's a problem with your commit. Left a comment here: https://github.com/lylek/stack/commit/6bb37bbba07d912da1304244ecbd2ce241c2c3eb.

**Comment by johnmendonca** [comment]
Ok, yeah I see what you mean.  I will take a look at this.

**Comment by johnmendonca** [comment]
Ok, I put that back how it was.

https://github.com/commercialhaskell/stack/compare/master...johnmendonca:4039-namespaced-templates

**Comment by lylek** [comment]
Looks good, thanks. I merged your branch into mine.

Now I'm thinking perhaps we need to modify existing unit tests or add a new one. I'm not sure this is very testable though, as it involves directly connecting to a remote URL.

**Comment by lylek** [comment]
I tweaked the help text a bit more and then submitted a pull request.

I also have updates for the documentation (on the web site), but apparently you're supposed to base that off the stable branch instead of master, so I guess that needs to be a separate pull request? Or can I do it in the same pull request? @snoyberg?

**Comment by lylek** [comment]
Never mind - I saw some other documentation that said to submit the doc changes with the code changes, so I canceled the first pull request, added the doc changes, and submitted a new one. The only thing is that I'm not sure how to build the docs, to make sure the output looks right.

**Comment by snoyberg** [comment]
You can check how the docs render on Github itself by clicking the `View` button:

https://github.com/lylek/stack/blob/2e143182d70a5ee2934db65094b9f704eb73fc10/doc/GUIDE.md

It looks good to me.

**Comment by lylek** [comment]
Great, thanks for the tip, Michael. I was a bit concerned because the contribution guide says "The documentation is rendered on haskellstack.org by readthedocs.org using Sphinx and CommonMark. Since links and formatting vary from GFM, please check the documentation there before submitting a PR to fix those." If it's different than GFM, I can't be sure that Github's rendering is accurate.

**Comment by snoyberg** [comment]
Oh, got it. Unfortunately, I don't think we can preview the readthedocs.org version. Anyway, don't worry about it, I've checked your Markdown, it should be fine. If not, we can always tweak it later.

**Comment by johnmendonca** [comment]
The pull request is looking good.  I would like to write a spec for the parsing done in TemplateName.  If this is ready to go I don't want to hold it up though.

**Comment by snoyberg** [comment]
Addressed via https://github.com/commercialhaskell/stack/pull/4103. @johnmendonca can you follow up with spec changes in a separate PR?

**Comment by johnmendonca** [comment]
@snoyberg Yep, no prob.  

@lylek Thanks for carrying this through.

**Comment by lylek** [comment]
@johnmendonca: You're welcome, thanks for your help. It just took a little while as I had to scrounge up bits of time here and there.

**Comment by johnmendonca** [comment]
Here is my first draft of a spec:

https://github.com/johnmendonca/stack/blob/4039-pt2-template-name-spec/src/test/Stack/Types/TemplateNameSpec.hs

I'm going to see if I can do this without `error`, or let me know if that is ok for specs in this case.

**Comment by snoyberg** [comment]
I don't see a problem with using `error` in this case.

**Comment by lylek** [comment]
Cool, thanks @johnmendonca. I was thinking it's difficult to test this because part of it is resolved from the structure of the TEMPLATE_NAME parameter itself, and part is resolved dynamically, by checking the filesystem and downloading remote URLs. But you've shown there was quite a bit to test just based on the structure of the parameter itself.

One slight problem with your spec: You show `"c:\\home\\file"` as resolving to relative, but on Windows it's an absolute path. You may need an `#if defined` statement as in https://www.stackage.org/haddock/lts-11.15/filepath-1.4.1.2/src/System-FilePath.html. Or maybe check `System.Info.arch`?

**Comment by johnmendonca** [comment]
@lylek Oh yeah, I meant to ask about that one.  `#if defined` sounds like the right approach.

**Comment by lylek** [comment]
@johnmendonca: I'm not sure. I guess `#if defined(mingw32_HOST_OS) || defined(__MINGW32__)` would be guaranteed to match exactly what `System.FilePath` is doing now. But it doesn't seem very clear, and it seems fragile, i.e., it seems like a list that could change. I guess if it fails in the future, this spec will be the first warning.

**Comment by snoyberg** [comment]
I'd actually probably lean away from CPP and use runtime checking (like `System.Info.arch`), as it makes it less likely to end up with code that's broken on one OS or the other.

**Comment by johnmendonca** [comment]
I went ahead and installed stack/haskell on windows to write this spec, and there were a few differences in parsing behavior:

https://github.com/johnmendonca/stack/blob/4039-pt2-template-name-spec/src/test/Stack/Types/TemplateNameSpec.hs

Paths with a colon bomb on windows unless is a drive letter, so I describe that on lines 38-41.  If that part looks clean enough to you guys, I will go ahead with a PR.

**Comment by lylek** [comment]
OK, that looks fine. I thought at first that on Windows it wasn't going to handle the 'gitlab:' type prefixes. But now I see it will handle those just fine, and will handle URLs, and will handle drive names like "c:", but will choke on other random things with a colon, because those can't be local file names. Seems reasonable.

**Comment by johnmendonca** [comment]
Thanks, sorry for taking my time on this, there is now a pull request: https://github.com/commercialhaskell/stack/pull/4168
